name: Build

on: [push]

runs:
  using: 'docker'
  image: 'Dockerfile'

jobs:
  build-unix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Dockerfile
        uses: ./
        id: build
